### ISSUE TITLE
server.js crashes

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mFiles#15]
There is an issue with the peering server that once a file is uploaded and someone attempts to access that file to download, server.js crashes and outputs this error

error: uncaughtException: Cannot read property 'token' of undefined date=Wed Dec 02 2015 21:47:16 GMT+0000 (UTC), pid=4653, uid=0, gid=0, cwd=/usr/share/reepio-peering-server, execPath=/usr/local/bin/node, version=v0.12.6, argv=[node, /usr/share/reepio-peering-server/src/server.js], rss=33148928, heapTotal=31598080, heapUsed=14325944, loadavg=[0.00439453125, 0.04541015625, 0.080078125], uptime=3790, trace=[column=36, file=/usr/share/reepio-peering-server/node_modules/peer/lib/server.js, function=handle, line=211, method=null, native=false, column=16, file=timers.js, function=timer._onTimeout, line=232, method=_onTimeout, native=false, column=15, file=timers.js, function=Timer.listOnTimeout, line=119, method=listOnTimeout, native=false], stack=[TypeError: Cannot read property 'token' of undefined,     at handle (/usr/share/reepio-peering-server/node_modules/peer/lib/server.js:211:36),     at timer._onTimeout (timers.js:232:16),     at Timer.listOnTimeout (timers.js:119:15)]

**Comment by MujiSayed** [comment]
this occurs when changing the config.js file in the public directory

from:
`host: window.location.hostname || 'peer.microhealthllc.com',`

to:

 `host: 'peer.microhealthllc.com',`

but this is required in order to fix the url generator bug
