### ISSUE TITLE
npm test error outputs

### ISSUE THREAD

**Issue by MujiSayed** [MicroHealthLLC/mFiles#17]
the basics are:

`PhantomJS 1.9.8 (Linux 0.0.0) common.crypto module common.crypto.crc32 function tests should return a hash for valid values FAILED
`

`PhantomJS 1.9.8 (Linux 0.0.0) download module tests DownloadCtrl should have a function "downloadFile" that starts the download FAILED
`

`PhantomJS 1.9.8 (Linux 0.0.0) peeringService tests peeringService.getPeer() service unavailable tests should throw an exception when peering-server is not available FAILED
`

the long version :

for firefox

`Firefox 42.0.0 (Windows 10 0.0.0) common.crypto module common.crypto.crc32 function tests should return a hash for valid values FAILED
        TypeError: expect(...).toNotBe is not a function
        @/usr/share/mFiles/tests/common/crypto_test.js:46:17
        invoke@/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3940:14
        workFn@/usr/share/mFiles/public/assets/js/angular-1.2.21/angular-mocks.js:2157:11
        angular.mock.inject@/usr/share/mFiles/public/assets/js/angular-1.2.21/angular-mocks.js:2142:25
        @/usr/share/mFiles/tests/common/crypto_test.js:45:57
        @/usr/share/mFiles/tests/common/crypto_test.js:28:9
        @/usr/share/mFiles/tests/common/crypto_test.js:26:5
        @/usr/share/mFiles/tests/common/crypto_test.js:22:2
Firefox 42.0.0 (Windows 10 0.0.0) download module tests DownloadCtrl should have a function "downloadFile" that starts the download FAILED
        minErr/<@/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:78:12
        forEach@/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:325:9
        loadModules@/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3846:5
        createInjector@/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3786:11
        workFn@/usr/share/mFiles/public/assets/js/angular-1.2.21/angular-mocks.js:2152:44
        loadModules/<@/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3880:15
        minErr/<@/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:78:12
        forEach@/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:325:9
        loadModules@/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3846:5
        createInjector@/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3786:11
        workFn@/usr/share/mFiles/public/assets/js/angular-1.2.21/angular-mocks.js:2152:44
        loadModules/<@/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3880:15
Firefox 42.0.0 (Windows 10 0.0.0) peeringService tests peeringService.getPeer() service unavailable tests should throw an exception when peering-server is not available FAILED
        minErr/<@/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:78:12
        forEach@/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:325:9
        loadModules@/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3846:5
        createInjector@/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3786:11
        workFn@/usr/share/mFiles/public/assets/js/angular-1.2.21/angular-mocks.js:2152:44
        loadModules/<@/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3880:15
        minErr/<@/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:78:12
        forEach@/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:325:9
        loadModules@/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3846:5
        createInjector@/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3786:11
        workFn@/usr/share/mFiles/public/assets/js/angular-1.2.21/angular-mocks.js:2152:44
        loadModules/<@/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3880:15
Firefox 42.0.0 (Windows 10 0.0.0): Executed 15 of 15 (3 FAILED) (0.108 secs / 0.072 secs)
`

for chrome:

`03 12 2015 20:58:13.631:INFO [Chrome 47.0.2526 (Windows 10 0.0.0)]: Connected on socket h36QX34bzRnIiY8lAAAA with id manual-2131
Chrome 47.0.2526 (Windows 10 0.0.0) common.crypto module common.crypto.crc32 function tests should return a hash for valid values FAILED
        TypeError: expect(...).toNotBe is not a function
            at Object.<anonymous> (/usr/share/mFiles/tests/common/crypto_test.js:46:51)
            at Object.invoke (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3940:17)
            at Object.workFn (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular-mocks.js:2157:20)
        Error: Declaration Location
            at window.inject.angular.mock.inject (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular-mocks.js:2142:25)
            at Suite.<anonymous> (/usr/share/mFiles/tests/common/crypto_test.js:45:57)
            at Suite.<anonymous> (/usr/share/mFiles/tests/common/crypto_test.js:28:9)
            at /usr/share/mFiles/tests/common/crypto_test.js:26:5
Chrome 47.0.2526 (Windows 10 0.0.0) download module tests DownloadCtrl should have a function "downloadFile" that starts the download FAILED
        Error: [$injector:modulerr] Failed to instantiate module peertome due to:
        Error: [$injector:nomod] Module 'peertome' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
        http://errors.angularjs.org/1.2.21/$injector/nomod?p0=peertome
            at /usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:78:12
            at /usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:1668:17
            at ensure (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:1592:38)
            at module (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:1666:14)
            at /usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3852:22
            at forEach (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:325:18)
            at loadModules (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3846:5)
            at Object.createInjector [as injector] (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3786:11)
            at Object.workFn (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular-mocks.js:2152:52)
        http://errors.angularjs.org/1.2.21/$injector/modulerr?p0=peertome&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'peertome'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.2.21%2F%24injector%2Fnomod%3Fp0%3Dpeertome%0A%20%20%20%20at%20http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2F/usr/share/mFiles%2Fpublic%2Fassets%2Fjs%2Fangular-1.2.21%2Fangular.js%3F64d89e5ba2111a94464361282c7a494d2975ff86%3A78%3A12%0A%20%20%20%20at%20http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2Fbase%2Fpublic%2Fassets%2Fjs%2Fangular-1.2.21%2Fangular.js%3F64d89e5ba2111a94464361282c7a494d2975ff86%3A1668%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2Fbase%2Fpublic%2Fassets%2Fjs%2Fangular-1.2.21%2Fangular.js%3F64d89e5ba2111a94464361282c7a494d2975ff86%3A1592%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2Fbase%2Fpublic%2Fassets%2Fjs%2Fangular-1.2.21%2Fangular.js%3F64d89e5ba2111a94464361282c7a494d2975ff86%3A1666%3A14)%0A%20%20%20%20at%20http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2Fbase%2Fpublic%2Fassets%2Fjs%2Fangular-1.2.21%2Fangular.js%3F64d89e5ba2111a94464361282c7a494d2975ff86%3A3852%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2Fbase%2Fpublic%2Fassets%2Fjs%2Fangular-1.2.21%2Fangular.js%3F64d89e5ba2111a94464361282c7a494d2975ff86%3A325%3A18)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2Fbase%2Fpublic%2Fassets%2Fjs%2Fangular-1.2.21%2Fangular.js%3F64d89e5ba2111a94464361282c7a494d2975ff86%3A3846%3A5)%0A%20%20%20%20at%20Object.createInjector%20%5Bas%20injector%5D%20(http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2Fbase%2Fpublic%2Fassets%2Fjs%2Fangular-1.2.21%2Fangular.js%3F64d89e5ba2111a94464361282c7a494d2975ff86%3A3786%3A11)%0A%20%20%20%20at%20Object.workFn%20(http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2Fbase%2Fpublic%2Fassets%2Fjs%2Fangular-1.2.21%2Fangular-mocks.js%3Fcad16e0e8de1e18da71df0a15fe0af24a8a7acc9%3A2152%3A52)%0A%20%20%20%20at%20attemptSync%20(http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F792589e7cd87cd2fd82e6c3c0cd543efb4a61d62%3A1886%3A24)
            at /usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:78:12
            at forEach (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:325:18)
            at loadModules (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3846:5)
            at Object.createInjector [as injector] (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3786:11)
            at Object.workFn (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular-mocks.js:2152:52)
            at /usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3880:15
        Error: [$injector:modulerr] Failed to instantiate module peertome due to:
        Error: [$injector:nomod] Module 'peertome' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
        http://errors.angularjs.org/1.2.21/$injector/nomod?p0=peertome
            at /usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:78:12
            at /usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:1668:17
            at ensure (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:1592:38)
            at module (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:1666:14)
            at /usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3852:22
            at forEach (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:325:18)
            at loadModules (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3846:5)
            at Object.createInjector [as injector] (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3786:11)
            at Object.workFn (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular-mocks.js:2152:52)
        http://errors.angularjs.org/1.2.21/$injector/modulerr?p0=peertome&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'peertome'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.2.21%2F%24injector%2Fnomod%3Fp0%3Dpeertome%0A%20%20%20%20at%20http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2F/usr/share/mFiles%2Fpublic%2Fassets%2Fjs%2Fangular-1.2.21%2Fangular.js%3F64d89e5ba2111a94464361282c7a494d2975ff86%3A78%3A12%0A%20%20%20%20at%20http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2Fbase%2Fpublic%2Fassets%2Fjs%2Fangular-1.2.21%2Fangular.js%3F64d89e5ba2111a94464361282c7a494d2975ff86%3A1668%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2Fbase%2Fpublic%2Fassets%2Fjs%2Fangular-1.2.21%2Fangular.js%3F64d89e5ba2111a94464361282c7a494d2975ff86%3A1592%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2Fbase%2Fpublic%2Fassets%2Fjs%2Fangular-1.2.21%2Fangular.js%3F64d89e5ba2111a94464361282c7a494d2975ff86%3A1666%3A14)%0A%20%20%20%20at%20http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2Fbase%2Fpublic%2Fassets%2Fjs%2Fangular-1.2.21%2Fangular.js%3F64d89e5ba2111a94464361282c7a494d2975ff86%3A3852%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2Fbase%2Fpublic%2Fassets%2Fjs%2Fangular-1.2.21%2Fangular.js%3F64d89e5ba2111a94464361282c7a494d2975ff86%3A325%3A18)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2Fbase%2Fpublic%2Fassets%2Fjs%2Fangular-1.2.21%2Fangular.js%3F64d89e5ba2111a94464361282c7a494d2975ff86%3A3846%3A5)%0A%20%20%20%20at%20Object.createInjector%20%5Bas%20injector%5D%20(http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2Fbase%2Fpublic%2Fassets%2Fjs%2Fangular-1.2.21%2Fangular.js%3F64d89e5ba2111a94464361282c7a494d2975ff86%3A3786%3A11)%0A%20%20%20%20at%20Object.workFn%20(http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2Fbase%2Fpublic%2Fassets%2Fjs%2Fangular-1.2.21%2Fangular-mocks.js%3Fcad16e0e8de1e18da71df0a15fe0af24a8a7acc9%3A2152%3A52)%0A%20%20%20%20at%20attemptSync%20(http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F792589e7cd87cd2fd82e6c3c0cd543efb4a61d62%3A1886%3A24)
            at /usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:78:12
            at forEach (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:325:18)
            at loadModules (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3846:5)
            at Object.createInjector [as injector] (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3786:11)
            at Object.workFn (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular-mocks.js:2152:52)
            at /usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3880:15
Chrome 47.0.2526 (Windows 10 0.0.0) peeringService tests peeringService.getPeer() service unavailable tests should throw an exception when peering-server is not available FAILED
        Error: [$injector:modulerr] Failed to instantiate module peertome due to:
        Error: [$injector:nomod] Module 'peertome' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
        http://errors.angularjs.org/1.2.21/$injector/nomod?p0=peertome
            at /usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:78:12
            at /usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:1668:17
            at ensure (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:1592:38)
            at module (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:1666:14)
            at /usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3852:22
            at forEach (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:325:18)
            at loadModules (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3846:5)
            at Object.createInjector [as injector] (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3786:11)
            at Object.workFn (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular-mocks.js:2152:52)
        http://errors.angularjs.org/1.2.21/$injector/modulerr?p0=peertome&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'peertome'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.2.21%2F%24injector%2Fnomod%3Fp0%3Dpeertome%0A%20%20%20%20at%20http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2F/usr/share/mFiles%2Fpublic%2Fassets%2Fjs%2Fangular-1.2.21%2Fangular.js%3F64d89e5ba2111a94464361282c7a494d2975ff86%3A78%3A12%0A%20%20%20%20at%20http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2Fbase%2Fpublic%2Fassets%2Fjs%2Fangular-1.2.21%2Fangular.js%3F64d89e5ba2111a94464361282c7a494d2975ff86%3A1668%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2Fbase%2Fpublic%2Fassets%2Fjs%2Fangular-1.2.21%2Fangular.js%3F64d89e5ba2111a94464361282c7a494d2975ff86%3A1592%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2Fbase%2Fpublic%2Fassets%2Fjs%2Fangular-1.2.21%2Fangular.js%3F64d89e5ba2111a94464361282c7a494d2975ff86%3A1666%3A14)%0A%20%20%20%20at%20http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2Fbase%2Fpublic%2Fassets%2Fjs%2Fangular-1.2.21%2Fangular.js%3F64d89e5ba2111a94464361282c7a494d2975ff86%3A3852%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2Fbase%2Fpublic%2Fassets%2Fjs%2Fangular-1.2.21%2Fangular.js%3F64d89e5ba2111a94464361282c7a494d2975ff86%3A325%3A18)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2Fbase%2Fpublic%2Fassets%2Fjs%2Fangular-1.2.21%2Fangular.js%3F64d89e5ba2111a94464361282c7a494d2975ff86%3A3846%3A5)%0A%20%20%20%20at%20Object.createInjector%20%5Bas%20injector%5D%20(http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2Fbase%2Fpublic%2Fassets%2Fjs%2Fangular-1.2.21%2Fangular.js%3F64d89e5ba2111a94464361282c7a494d2975ff86%3A3786%3A11)%0A%20%20%20%20at%20Object.workFn%20(http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2Fbase%2Fpublic%2Fassets%2Fjs%2Fangular-1.2.21%2Fangular-mocks.js%3Fcad16e0e8de1e18da71df0a15fe0af24a8a7acc9%3A2152%3A52)%0A%20%20%20%20at%20attemptSync%20(http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F792589e7cd87cd2fd82e6c3c0cd543efb4a61d62%3A1886%3A24)
            at /usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:78:12
            at forEach (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:325:18)
            at loadModules (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3846:5)
            at Object.createInjector [as injector] (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3786:11)
            at Object.workFn (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular-mocks.js:2152:52)
            at /usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3880:15
        Error: [$injector:modulerr] Failed to instantiate module peertome due to:
        Error: [$injector:nomod] Module 'peertome' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
        http://errors.angularjs.org/1.2.21/$injector/nomod?p0=peertome
            at /usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:78:12
            at /usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:1668:17
            at ensure (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:1592:38)
            at module (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:1666:14)
            at /usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3852:22
            at forEach (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:325:18)
            at loadModules (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3846:5)
            at Object.createInjector [as injector] (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3786:11)
            at Object.workFn (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular-mocks.js:2152:52)
        http://errors.angularjs.org/1.2.21/$injector/modulerr?p0=peertome&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'peertome'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.2.21%2F%24injector%2Fnomod%3Fp0%3Dpeertome%0A%20%20%20%20at%20http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2F/usr/share/mFiles%2Fpublic%2Fassets%2Fjs%2Fangular-1.2.21%2Fangular.js%3F64d89e5ba2111a94464361282c7a494d2975ff86%3A78%3A12%0A%20%20%20%20at%20http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2Fbase%2Fpublic%2Fassets%2Fjs%2Fangular-1.2.21%2Fangular.js%3F64d89e5ba2111a94464361282c7a494d2975ff86%3A1668%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2Fbase%2Fpublic%2Fassets%2Fjs%2Fangular-1.2.21%2Fangular.js%3F64d89e5ba2111a94464361282c7a494d2975ff86%3A1592%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2Fbase%2Fpublic%2Fassets%2Fjs%2Fangular-1.2.21%2Fangular.js%3F64d89e5ba2111a94464361282c7a494d2975ff86%3A1666%3A14)%0A%20%20%20%20at%20http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2Fbase%2Fpublic%2Fassets%2Fjs%2Fangular-1.2.21%2Fangular.js%3F64d89e5ba2111a94464361282c7a494d2975ff86%3A3852%3A22%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2Fbase%2Fpublic%2Fassets%2Fjs%2Fangular-1.2.21%2Fangular.js%3F64d89e5ba2111a94464361282c7a494d2975ff86%3A325%3A18)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2Fbase%2Fpublic%2Fassets%2Fjs%2Fangular-1.2.21%2Fangular.js%3F64d89e5ba2111a94464361282c7a494d2975ff86%3A3846%3A5)%0A%20%20%20%20at%20Object.createInjector%20%5Bas%20injector%5D%20(http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2Fbase%2Fpublic%2Fassets%2Fjs%2Fangular-1.2.21%2Fangular.js%3F64d89e5ba2111a94464361282c7a494d2975ff86%3A3786%3A11)%0A%20%20%20%20at%20Object.workFn%20(http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2Fbase%2Fpublic%2Fassets%2Fjs%2Fangular-1.2.21%2Fangular-mocks.js%3Fcad16e0e8de1e18da71df0a15fe0af24a8a7acc9%3A2152%3A52)%0A%20%20%20%20at%20attemptSync%20(http%3A%2F%2Ffiles.microhealthllc.com%3A9876%2Fbase%2Fnode_modules%2Fjasmine-core%2Flib%2Fjasmine-core%2Fjasmine.js%3F792589e7cd87cd2fd82e6c3c0cd543efb4a61d62%3A1886%3A24)
            at /usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:78:12
            at forEach (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:325:18)
            at loadModules (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3846:5)
            at Object.createInjector [as injector] (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3786:11)
            at Object.workFn (/usr/share/mFiles/public/assets/js/angular-1.2.21/angular-mocks.js:2152:52)
            at /usr/share/mFiles/public/assets/js/angular-1.2.21/angular.js:3880:15
Chrome 47.0.2526 (Windows 10 0.0.0): Executed 15 of 15 (3 FAILED) (0.076 secs / 0.04 secs)
`

**Comment by MujiSayed** [comment]
also recieved this:
`Error: [$injector:modulerr] Failed to instantiate module peertome due to:
bash: Error:: command not found
`

`
 Error: [$injector:nomod] Module 'peertome' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
`
