### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mFiles#4]
doesn't work. did npm update and npm start. changed the config to peer.microhealthllc.com didn't work. then changed to localhost didn't work. I'm looking really have both the file server and peering server install with an npm update and npm start and voila...it works. Its stuck at loading see the image below
![stuck at loading](https://cloud.githubusercontent.com/assets/3675043/8513728/8a597850-2344-11e5-8311-2e4787a3bba0.png)

**Comment by bluenevus** [comment]
this looks to be a problem connecting to the peering server but not sure.  Either way...doesn't load

**Comment by bluenevus** [comment]
stdout:
stderr:  2015-07-09T12:50:42.053Z - error: uncaughtException: Cannot read property 'load' of undefined date=Thu Jul 09 2015 12:50:42 GMT+00             00 (UTC), pid=3533, uid=0, gid=0, cwd=/home/admin/mFiles, execPath=/usr/local/bin/node, version=v0.12.2, argv=[node, /home/admin/mFiles/src             /server.js], rss=29130752, heapTotal=20125696, heapUsed=13397224, loadavg=[1.57763671875, 1.95361328125, 1.21826171875], uptime=845, trace=             [column=21, file=/home/admin/mFiles/src/config.js, function=onSuccess, line=48, method=null, native=false, column=54, file=/home/admin/mFil             es/node_modules/q/q.js, function=_fulfilled, line=834, method=null, native=false, column=30, file=/home/admin/mFiles/node_modules/q/q.js, f             unction=self.promiseDispatch.done, line=863, method=promiseDispatch.done, native=false, column=13, file=/home/admin/mFiles/node_modules/q/q             .js, function=Promise.promise.promiseDispatch, line=796, method=promise.promiseDispatch, native=false, column=44, file=/home/admin/mFiles/n             ode_modules/q/q.js, function=null, line=604, method=null, native=false, column=13, file=/home/admin/mFiles/node_modules/q/q.js, function=ru             nSingle, line=137, method=null, native=false, column=13, file=/home/admin/mFiles/node_modules/q/q.js, function=flush, line=125, method=null             , native=false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[TypeError: C             annot read property 'load' of undefined,     at onSuccess (/home/admin/mFiles/src/config.js:48:21),     at _fulfilled (/home/admin/mFiles/n             ode_modules/q/q.js:834:54),     at self.promiseDispatch.done (/home/admin/mFiles/node_modules/q/q.js:863:30),     at Promise.promise.promis             eDispatch (/home/admin/mFiles/node_modules/q/q.js:796:13),     at /home/admin/mFiles/node_modules/q/q.js:604:44,     at runSingle (/home/ad             min/mFiles/node_modules/q/q.js:137:13),     at flush (/home/admin/mFiles/node_modules/q/q.js:125:13),     at process._tickCallback (node.js             :355:11)]

exec error:  { [Error: Command failed: /bin/sh -c node src/server.js
2015-07-09T12:50:42.053Z - error: uncaughtException: Cannot read property 'load' of undefined date=Thu Jul 09 2015 12:50:42 GMT+0000 (UTC),              pid=3533, uid=0, gid=0, cwd=/home/admin/mFiles, execPath=/usr/local/bin/node, version=v0.12.2, argv=[node, /home/admin/mFiles/src/server.j             s], rss=29130752, heapTotal=20125696, heapUsed=13397224, loadavg=[1.57763671875, 1.95361328125, 1.21826171875], uptime=845, trace=[column=2             1, file=/home/admin/mFiles/src/config.js, function=onSuccess, line=48, method=null, native=false, column=54, file=/home/admin/mFiles/node_m             odules/q/q.js, function=_fulfilled, line=834, method=null, native=false, column=30, file=/home/admin/mFiles/node_modules/q/q.js, function=s             elf.promiseDispatch.done, line=863, method=promiseDispatch.done, native=false, column=13, file=/home/admin/mFiles/node_modules/q/q.js, func             tion=Promise.promise.promiseDispatch, line=796, method=promise.promiseDispatch, native=false, column=44, file=/home/admin/mFiles/node_modul             es/q/q.js, function=null, line=604, method=null, native=false, column=13, file=/home/admin/mFiles/node_modules/q/q.js, function=runSingle,              line=137, method=null, native=false, column=13, file=/home/admin/mFiles/node_modules/q/q.js, function=flush, line=125, method=null, native=             false, column=11, file=node.js, function=process._tickCallback, line=355, method=_tickCallback, native=false], stack=[TypeError: Cannot rea             d property 'load' of undefined,     at onSuccess (/home/admin/mFiles/src/config.js:48:21),     at _fulfilled (/home/admin/mFiles/node_modul             es/q/q.js:834:54),     at self.promiseDispatch.done (/home/admin/mFiles/node_modules/q/q.js:863:30),     at Promise.promise.promiseDispatch              (/home/admin/mFiles/node_modules/q/q.js:796:13),     at /home/admin/mFiles/node_modules/q/q.js:604:44,     at runSingle (/home/admin/mFile             s/node_modules/q/q.js:137:13),     at flush (/home/admin/mFiles/node_modules/q/q.js:125:13),     at process._tickCallback (node.js:355:11)]
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c node src/server.js' }

**Comment by bluenevus** [comment]
remove it, do a clean install and see the errors.  It can't find the /signaling directory either
